title: "Partner Resources"
author: Microsoft
description: Resources created by Microsoft's GPS (Global Partner Solutions) team
baseurl: "/PartnerResources"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Microsoft"

# Social (First three Required)
repo: "https://github.com/Azure/arc_jumpstart_docs"
github_user: "Azure"
github_repo: "arc_jumpstart_docs"
github_branch: "main"
twitter: Azure
linkedin: Azure

logo_pixels: 50
color: "#0078D4"

# show related plans on learning plans
showrelatedplans: true

# include app insights
includeappinsights: true

# google-analytics: UA-XXXXXXXXXX
# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/AzureArcJumpstart-square-blue.png"

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://azurearcjumpstart.io/search?q=
# tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: "#0078D4"
themeColor: "#0078D4"
fixedNav: 'true' # true or false

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links