name: repoTraffic

#on:
  #push:
    #branches: [ main ]
    
on:
  schedule: 
    # runs once a week on Saturday: https://crontab.cronhub.io/
    - cron: "0 0 * * SAT"
    
  # Enables the workflow to be started manually
  workflow_dispatch:
    
jobs:
  # This workflow contains a single job called "traffic"
  save-traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "traffic"
    
    # Calculates traffic and clones and stores in CSV file
    - name: GitHub traffic 
      uses: sangonzal/repository-traffic-action@v0.1.3
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Santiago Gonzalez
        message: "GitHub traffic"
        add: "./traffic/*"
        ref: "traffic"  # commits to branch "traffic" 
